application: nebree8
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: static/menu.html
  upload: static/menu.html
- url: /
  static_dir: static
